### Sign up
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"hello"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"admin@mail.com",
    "password":"hello"
}

### Sign out
POST http://localhost:3000/auth/signout
Content-Type: application/json


### Get me
GET http://localhost:3000/auth/me
Content-Type: application/json


### Find a user with id
GET http://localhost:3000/auth/1


### Find all users with email
GET http://localhost:3000/auth?email=cd@mail.com


### Delete a user with id
DELETE http://localhost:3000/auth/1


### Update an user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email":"aa@mail.com"
}
